/**
 * Reading a contract that never published its source.
 *
 * The accuracy benchmark made the case for this file. Of the drainer addresses
 * sampled from a public list, seven of eight had no published source, so the
 * only thing the tool could say was "the code was never published" — true, but
 * weak, and it meant the blocklist was carrying the whole product.
 *
 * Compiled EVM bytecode still names its functions. Solidity's dispatcher
 * compares the incoming call against each function's 4-byte selector with a
 * PUSH4, so the selectors are sitting there in plain sight even when the source
 * is not. We cannot read the logic, but we can read the interface — and an
 * unverified contract whose interface is `SecurityUpdate()` and `Claim()` is
 * worth saying something about.
 *
 * Selectors are generated by scripts/selectors.py, which implements Keccak-256
 * (Python ships NIST SHA3, which differs by one padding byte and yields wrong
 * selectors) and refuses to print anything until it reproduces published values
 * such as transferFrom -> 0x23b872dd.
 *
 * These stay CAUTION-tier capabilities, never facts. A legitimate airdrop
 * contract can have a Claim() function, and a false alarm on a real token costs
 * more than a missed warning here.
 */

import type { CheckContext, Finding } from "../types";

/** Names that essentially only appear on wallet-drainer phishing contracts. */
const DRAINER_BAIT: Record<string, string> = {
  "0x5fba79f5": "SecurityUpdate()",
  "0x593dae5b": "SecurityUpdate(address)",
  "0x3158952e": "Claim()",
  "0x0c7ef932": "Claim(address)",
  "0x12798972": "ClaimRewards()",
  "0x79372f9a": "ClaimReward()",
  "0xa16f15c3": "Connect()",
  "0x143087ee": "Verify()",
  "0x3f6b6f2e": "Airdrop()",
};

/** Ways to move other people's balances. */
const SWEEPING: Record<string, string> = {
  "0xac9650d8": "multicall(bytes[])",
  "0x8d80ff0a": "multiSend(bytes)",
  "0xd505accf": "permit(...)",
};

/** Owner powers, readable without source. Keyed by the family they belong to. */
const OWNER_POWERS: { selector: string; signature: string; family: string; reason: string }[] = [
  {
    selector: "0x40c10f19",
    signature: "mint(address,uint256)",
    family: "mint",
    reason:
      "The code was never published, and it contains a function that creates new tokens. Nobody outside the project can see who is allowed to call it.",
  },
  {
    selector: "0x8456cb59",
    signature: "pause()",
    family: "ownership",
    reason:
      "The code was never published, and it contains a function that can stop everyone moving this token.",
  },
  {
    selector: "0xf9f92be4",
    signature: "blacklist(address)",
    family: "honeypot",
    reason:
      "The code was never published, and it contains a function that can freeze a wallet. You cannot see the rules for when it is used.",
  },
  {
    selector: "0x0ecb93c0",
    signature: "addBlackList(address)",
    family: "honeypot",
    reason:
      "The code was never published, and it contains a function that can freeze a wallet. You cannot see the rules for when it is used.",
  },
  {
    selector: "0x153b0d1e",
    signature: "setBlacklist(address,bool)",
    family: "honeypot",
    reason:
      "The code was never published, and it contains a function that can freeze a wallet. You cannot see the rules for when it is used.",
  },
  {
    selector: "0x3659cfe6",
    signature: "upgradeTo(address)",
    family: "ownership",
    reason:
      "The code was never published, and it can be swapped for different code later.",
  },
  {
    selector: "0x4f1ef286",
    signature: "upgradeToAndCall(address,bytes)",
    family: "ownership",
    reason:
      "The code was never published, and it can be swapped for different code later.",
  },
];

/**
 * Pull the 4-byte selectors out of compiled bytecode.
 *
 * Solidity's dispatcher emits PUSH4 (0x63) followed by the selector for each
 * external function. Scanning for that finds far more than it misses, and a
 * stray match is harmless: we only ever look up selectors we care about.
 */
export function extractSelectors(bytecode: string): Set<string> {
  const hex = bytecode.startsWith("0x") ? bytecode.slice(2) : bytecode;
  const found = new Set<string>();

  for (let i = 0; i + 10 <= hex.length; i += 2) {
    if (hex.slice(i, i + 2).toLowerCase() !== "63") continue;
    found.add(`0x${hex.slice(i + 2, i + 10).toLowerCase()}`);
  }

  return found;
}

export function bytecodeChecks(ctx: CheckContext): Finding[] {
  // Source, where we have it, says more than an interface ever could.
  if (ctx.verified || !ctx.bytecode || ctx.bytecode.length <= 2) return [];

  const selectors = extractSelectors(ctx.bytecode);
  const findings: Finding[] = [];

  const bait = Object.entries(DRAINER_BAIT)
    .filter(([selector]) => selectors.has(selector))
    .map(([, signature]) => signature);

  if (bait.length > 0) {
    findings.push({
      id: "approvals.drainer_interface",
      kind: "capability",
      severity: "high",
      humanReason:
        "This has unpublished code with buttons named like the ones on fake airdrop and \"wallet security\" pages. Real projects do not need you to run a security update.",
      evidence: `unpublished code exposes ${bait.join(", ")}`,
    });
  }

  const sweeping = Object.entries(SWEEPING)
    .filter(([selector]) => selectors.has(selector))
    .map(([, signature]) => signature);

  if (sweeping.length > 0) {
    findings.push({
      id: "approvals.batch_interface",
      kind: "capability",
      severity: "medium",
      humanReason:
        "This has unpublished code that can move tokens out of several wallets in one transaction. Payment tools work this way; so do drainers.",
      evidence: `unpublished code exposes ${sweeping.join(", ")}`,
    });
  }

  for (const power of OWNER_POWERS) {
    if (!selectors.has(power.selector)) continue;
    // One finding per family, not one per spelling of the same power.
    if (findings.some((f) => f.id === `${power.family}.unpublished_power`)) continue;

    findings.push({
      id: `${power.family}.unpublished_power`,
      kind: "capability",
      severity: "medium",
      humanReason: power.reason,
      evidence: `unpublished code exposes ${power.signature}`,
    });
  }

  return findings;
}
